#' Update package logo
#'
#' @description
#' This function is meant for generating or updating the logo. After running
#' this procedure we end up with what is stored in the `LOGO` constant.
#'
#' @param template A character string representing the path to the logo
#' template.
#'
#' @param version A numerical vector of three positive integers representing the
#' version of the package to append to the logo.
#'
#' @return The ASCII logo.
#'
#' @keywords internal
#'
#' @export
make_logo <- function(template = "./inst/assets/logo/powerly-logo.txt", version = c(2, 0, 0)) {
    # Load the ASCII logo.
    logo <- readLines(template)

    # Create a text connection.
    connection <- textConnection(NULL, open = "w", local = TRUE)

    # Close the connection on exit.
    on.exit({
        # Close.
        close(connection)
    })

    # Redirect console output.
    sink(connection, type = "output")

    # Parse the logo.
    logo <- dput(logo)

    # Remove output redirection.
    sink(NULL)

    # Update versioning.
    logo <- gsub("{{major}}", version[1], logo, perl = TRUE)
    logo <- gsub("{{minor}}", version[2], logo, perl = TRUE)
    logo <- gsub("{{patch}}", version[3], logo, perl = TRUE)

    # Condensed version.
    logo <- paste(logo, collapse = "\n")

    return(logo)
}


#' @title
#' The Package Logo
#'
#' @description
#' The logo is generated by [powerly::make_logo()] and displayed on package
#' attach for interactive `R` sessions.
#'
#' @format
#' An object of class `character` containing the `ASCII` logo.
#'
#' @examples
#' print(LOGO)
#'
#' @seealso [powerly::make_logo()]
#'
#' @export
LOGO = ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n.                                            _     v2.x.x .\n.                                           | |           .\n.   _ __     ___   __      __   ___   _ __  | |  _   _    .\n.  | '_ \\   / _ \\  \\ \\ /\\ / /  / _ \\ | '__| | | | | | |   .\n.  | |_) | | (_) |  \\ V  V /  |  __/ | |    | | | |_| |   .\n.  | .__/   \\___/    \\_/\\_/    \\___| |_|    |_|  \\__, |   .\n.  | |                                            __/ |   .\n.  |_|                                           |___/    .\n.                                                         .\n. . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n.                            .                            .\n.                   https://powerly.dev                   .\n.                            .                            .\n. . . . . . . . . . . . . . . . . . . . . . . . . . . . . ."


# Add package logo class.
class(LOGO) <- "powerly"


# Add S3 method for properly printing the logo.
#' @export
print.powerly <- function(x, ...) {
    # Print the logo.
    cat(LOGO, sep = "")
}
