# Workflow name.
name: docs

# Events.
on:
  # Trigger on push to branch.
  push:
    branches: [main]
  # Trigger manually via the GitHub UI.
  workflow_dispatch:

# Jobs.
jobs:
  docs:
    # Virtual machine type.
    runs-on: ubuntu-latest

    # Job steps.
    steps:
      # Fetch all commits to get all `.git` info logs.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install `pnmp`.
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      # Install `Node.js`.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: pnpm

      # Run build script.
      - name: Build VuePress site
        run: pnpm docs:build

      # Deploy website.
      # https://github.com/crazy-max/ghaction-github-pages.
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # Deploy to `gh-pages` branch.
          target_branch: gh-pages
          # Deploy the default output dir of VuePress.
          build_dir: docs/.vuepress/dist
          # Write the given domain name to the CNAME file.
          fqdn: powerly.dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
