# Workflow name.
name: test-coverage

# Events.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs.
jobs:

  # Test coverage job.
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    # Actions.
    steps:
      # Checkout.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup `R`.
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install `powerly` dependencies and `covr` package.
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      # Run the test coverage excluding specific lines.
      - name: Test coverage
        run: |
          covr::codecov(
            line_exclusions = list(
              # Irrelevant.
              "R/powerly-package.R",
              "R/constants.R",
              "R/logo.R",
              "R/helpers.R",

              # Ignore plotting functions for now.
              "R/methods.R" = c(1:639, 679:717),

              # Ignore active bindings.
              "R/Basis.R" = c(62:68),
              "R/StepTwo.R" = c(161:170),
              "R/Range.R" = c(83:93),
              "R/Validation.R" = c(90:107),
              "R/Method.R" = c(183:208),
              "R/StepThree.R" = c(252:284, 287:299)
            )
          )
        shell: Rscript {0}
